"""v9.11 compression pass: trim ~600 words, move probe-level detail to supplementary pointers.
Anchor-based full-paragraph replacement; preserves all checklist tokens."""
from docx import Document

SRC = 'Manuscript_EC_methylation_panel_v9.11.docx'

REWRITES = [
("Results: TCGA and GSE67116 yielded",
 "Results: TCGA and GSE67116 yielded 23,099 and 292 DMRs; 50 DMRs and 476 elite probes passed cross-cohort consistency and entry criteria. Background estimates were higher in the intended-use-proxy cohort than in a small cancer-free endometrial reference cohort (approximately 1.2- to 1.6-fold). One probe was assessable in all five background dimensions: cg24589459 (BOLL; Δβ=0.533, premenopausal positivity 89.3%), which met the prespecified 0.15 background gate by point estimate, although its bootstrap confidence interval crossed the threshold (borderline). cg27577527 (ZSCAN12; Δβ=0.614, positivity 92.9%) passed the four dimensions measurable at probe level and showed the most consistently low background; the intended-use-proxy dimension is not directly assessable because the probe is absent from the EPIC platform, and support there is indirect and region-level only, through EPIC-compatible substitute probes whose own compliance was pipeline-dependent. Probe-level corroboration in three independent tumour-tissue cohorts—not the intended sampling compartments—partially supported the candidates and, for BOLL, generated a post hoc two-probe region-level hypothesis to be locked prospectively; no cross-cohort ROC metric is reported because case and control series come from different studies. No statistically significant menopause-associated differences were detected (28 premenopausal versus 345 postmenopausal tumours), although the analysis was underpowered and equivalence was not established. Tumour–normal differences were essentially unchanged after adjustment for age and histological type (maximum change in Δβ 0.03). Background point estimates and near-gate pass/fail status were pipeline-dependent (11 of 26 probes changed between noob and GMQN; both lead probes robust), so the fixed β thresholds are heuristic screening rules, not cross-platform constants. These in silico estimates derive partly from discovery data and are upper bounds; the candidates are not a validated panel."),

("IDATs were processed with minfi",
 "IDATs were processed with minfi [16] (noob normalisation; samples retained when <10% of probes had detection P>0.01; probes excluded for detection failure, sex chromosomes or common SNPs), yielding 466,130 (GSE67116) and 464,285 (GSE73949) probes. DMPs were identified with limma [17] on M-values. DMRs were defined with a deterministic comb-p-like algorithm [18]: same-direction significant probes (FDR<0.05) within 500 bp were merged, regions with ≥3 probes retained, and region-level Stouffer P values computed. Region-level P values were used only for candidate generation, not interpreted as calibrated confirmatory evidence; final selection was driven by effect size, tumour positivity and background gates. Contrasts were TCGA tumour versus adjacent normal (unpaired, 431 versus 46; unadjusted, effect-size filtering being the primary criterion) and GSE67116 primary tumour versus hyperplasia; cross-cohort consistency was assessed at the effect-size level, the eight-sample hyperplasia group limiting formal DMR power. Because this implementation does not model inter-probe correlation (potentially anti-conservative region P values), the two lead regions were re-tested with bumphunter (B=500 permutations; maxGap 500 bp; chromosome-wide permutation nulls on chr2 and chr6, giving chromosome-wise—not genome-wide—significance with minimum reportable empirical P of 1/501 ≈ 0.002). Both BOLL-region probes map uniquely to the BOLL locus and carry no common SNPs at CpG or single-base-extension sites [28] (Supplementary Data), making cross-mapping an unlikely explanation for their discordant behaviour; residual cross-reactivity cannot be excluded by annotation alone."),

("Analyses used R 4.6.0",
 "Analyses used R 4.6.0 (minfi 1.58.0, limma 3.68.4, bumphunter 1.54.0) and Python 3.13. Background P95 used linear-interpolation quantiles (R type 7). Group comparisons used limma moderated statistics on M-values; β values were used for positivity and background summaries; P values were Benjamini–Hochberg adjusted. Discovery-layer β values combined Xena-precomputed TCGA data with noob-normalised GSE67116 data, whereas background triage used GMQN-normalised values; because of this mismatch all thresholds were set empirically, and final thresholds will be established in a prospectively collected cohort processed with one predefined pipeline (see Limitations). Background P95 confidence intervals were estimated by 10,000-draw non-parametric bootstrap; positivity rates are reported with Wilson score intervals. Menopause-stratified analyses compared 28 premenopausal with 345 postmenopausal TCGA tumours (Welch t on M-values; Fisher exact on positivity; exploratory tissue×menopause interaction). Thirty-three patient-matched tumour–normal pairs were analysed by Wilcoxon signed-rank tests; molecular subtypes were taken from the PanCanAtlas annotations via cBioPortal. Candidate retention was scanned across background P95 gates of 0.05–0.30. Confounder sensitivity used limma models on M-values adjusting for age and histological type (three-level tissue factor), an endometrioid-only age-adjusted model, and a tumour-only subtype-association model. Pipeline sensitivity reprocessed the GSE73949 and GSE67116 IDATs under raw and noob pipelines against the GMQN values used in triage."),

("Background P95 β values in the benign endometrial cohort",
 "Background P95 β values in the benign endometrial cohort approximating the intended-use population (n=347) were higher than in healthy premenopausal donors (n=17). Because this contrast spans platform (450K versus EPIC) and normalisation (noob versus GMQN), we decomposed it in an EPIC/GMQN-aligned comparison (same platform and normalisation, different cohorts and centres): the benign cohort remained consistently elevated relative to cancer-free endometrial controls (n=13; e.g., P95 β 0.100 versus 0.059 for cg24589459, 0.372 versus 0.252 for CDO1), approximately 1.2- to 1.6-fold, so the raw two- to three-fold contrast is inflated by processing while the qualitative difference persists (cohort, centre and residual processing effects cannot be fully separated; reference n=13). Endometriosis samples (n=637) showed per-probe P95 values comparable to—and consistently slightly below—those of the 347 controls (per-group values in Supplementary Data), so the control-based gate is the conservative choice for this dimension. A union rule requiring P95 β≤0.15 in every assessable cohort left two probes (below); for cg27577527 (ZSCAN12), the intended-use-proxy dimension was not directly assessable because the probe is absent from EPIC arrays."),

("The two lead probes differ in evidentiary status",
 "The two lead probes differ in evidentiary status. cg24589459 (BOLL) is the only probe assessable in all five dimensions: background P95 β 0.100–0.141 across dimensions (bootstrap 95% CI at the limiting cervical dimension 0.100–0.158; a point-estimate pass whose confidence interval crosses the 0.15 gate—borderline), Δβ=0.533, premenopausal positivity 89.3% (Wilson 95% CI 72.8–96.3%). cg27577527 (ZSCAN12) passed the four dimensions measurable at probe level (P95 β 0.044–0.060; Δβ=0.614; positivity 92.9%) and showed the most consistently low background; the decisive intended-use-proxy dimension is not directly assessable because the probe is absent from EPIC arrays, and its compliance there is supported only indirectly, at region level, by the EPIC-compatible substitutes described below. We therefore do not claim five-dimension compliance for ZSCAN12. Tier-B candidates were cg15790037 (ARL5C), cg16439198 (CYP1B1), cg23180938 (CDO1), cg18507379 (PCDHGA cluster) and cg10109500 (GHSR) (Table 4). The BOLL partner probe cg07495363 alone detected all 28 premenopausal tumours in silico (anchor 25/28), greedy coverage reaching 99.8% after two additions—a within-training-set estimate, optimistic by construction. A 23-probe experimental candidate pool (7 tier-A/B leads plus 16 region-coverage probes, 15 of which additionally passed the narrower cervix–blood–cycle gate; list, coordinates and primer annotations in Supplementary Data), none carrying annotated common SNPs at CpG or single-base-extension sites [28] and 22/23 embedded in multi-CpG DMRs, is proposed for targeted bisulfite validation. Menstrual-cycle drift of the anchor probe was minimal (mean |Δβ| 0.026 between fingerprint-paired early- and mid-secretory samples; full-panel range 0.014–0.042); proliferative-phase, menstrual and anovulatory states were not assayed."),

("Threshold sensitivity analysis distinguished",
 "Threshold sensitivity analysis distinguished ranking stability from strict gate compliance (Figure 5). Candidate rankings were stable across background gates of 0.10–0.20 and composite-score weight perturbations (7–9 of the top-10 probes unchanged; Supplementary Data), but strict all-dimension compliance was threshold-dependent: cg27577527 passed every assessable dimension down to a gate of 0.09, whereas cg24589459 entered only at gates ≥0.15 (cervical-scrape P95 0.141; bootstrap 95% CI 0.100–0.158) and is accordingly classified as borderline at the primary 0.15 gate. Final cut-offs must be set empirically in the validation cohort."),

("Cross-pipeline consistency.",
 "Cross-pipeline consistency. Because discovery and triage combined Xena-precomputed TCGA β values, noob-processed IDATs and GMQN-normalised matrices, we tested how preprocessing affects the fixed-threshold gates. Reprocessing the GSE73949 IDATs (n=17) under raw and noob pipelines and comparing with GMQN values shifted background P95 point estimates by a median of 0.022 (maximum 0.045) and changed pass/fail status at the 0.15 gate for 11 of 26 probes between noob and GMQN—all near-gate probes (P95 0.125–0.178 across pipelines). Both lead probes were robust (cg24589459 and cg27577527 passed under every pipeline; noob P95 0.110 and 0.060, GMQN 0.131 and 0.085). The three ZSCAN12 substitutes passed under noob but exceeded the gate under GMQN (P95 0.160–0.167), so their healthy-endometrium compliance is pipeline-dependent and unresolved. Tumour–hyperplasia Δβ rankings in GSE67116 were highly consistent between raw and noob (Spearman ρ=0.98). Candidate ranking is thus stable across mainstream pipelines, but absolute pass/fail status near the gate is pipeline-bound—reinforcing that the fixed thresholds are heuristic screening rules and that final cut-offs must be locked under one predefined pipeline."),

("Menopause-stratified, matched-pair and subtype sensitivity",
 "Menopause-stratified, matched-pair and subtype sensitivity analyses in TCGA. No statistically significant menopause-associated differences were detected at the 26 probes of the extended sensitivity set (28 premenopausal versus 345 postmenopausal tumours): per-probe mean-β differences ranged from −0.13 to +0.05 (largest decrease cg10617784, −0.131, 95% CI −0.224 to −0.038), none significant after Benjamini–Hochberg correction (minimum FDR 0.17), and positivity rates did not differ. The analysis was underpowered and equivalence was not established; the tissue×menopause interaction is exploratory (only two adjacent normals were premenopausal; Supplementary Data). In 33 patient-matched tumour–normal pairs, all 26 probes were hypermethylated in tumours (mean paired Δβ 0.46–0.70; ≥91% of pairs concordant; Wilcoxon FDR<0.01): the signal persists patient-matched, although tumour purity, cell composition, batch and field effects remain as residual confounders. The signal also persisted in the endometrioid-only subset (n=333; Δβ 0.44–0.67) and across all four molecular subtypes (Δβ 0.34–0.71). Adjustment changed these estimates minimally: all 26 probes remained significant (FDR<0.05) in age-adjusted and age-plus-histology-adjusted limma models (adjusted versus unadjusted logFC Pearson r=0.97–0.99; maximum change in Δβ 0.03), and an endometrioid-only age-adjusted model was concordant. Within tumours, methylation magnitude varied by molecular subtype (subtype F-test FDR<0.05 for all 26 probes), consistent with known subtype-associated global methylation differences. Both lead regions were recovered by an alternative permutation-based DMR method in the same dataset (bumphunter; chromosome-wise empirical P≤0.002, the minimum reportable at B=500): cross-method corroboration within TCGA, not independent confirmation. These comparisons cannot establish premenopausal assay specificity, which requires the purpose-built cohort described below."),

("Of the 23 panel probes, 21 are present",
 "Of the 23 panel probes, 21 are present on the EPIC manifest (exceptions cg27577527 [ZSCAN12] and cg20998319); cg27577527 was therefore not evaluable externally. In the full 103-sample GSE136791 series, 13 of 21 evaluable probes reached ≥80% positivity (β>0.3); restricting to the 69 carcinomas, 16 of 21 reached ≥80%, including six at ≥94% and the BOLL anchor cg24589459 at 87.0% (Table 8). In the 23 endometrioid EC samples of GSE155760, positivity was broadly reproducible (91.3–95.7%) but lower for cg24589459 (65.2%), whereas the 13 endometrial controls showed a markedly low background for cg24589459 (P95 β=0.025; 0/13 above β 0.3 for either BOLL probe, Wilson 95% CI 0–22.8%) compared with cg07495363 (0.270) (Table 8). This dissociation indicates complementary behaviour within the region—cg24589459 low-false-positive, cg07495363 high-sensitivity—and constitutes a post hoc, hypothesis-generating observation made after inspecting these external data; it motivates our proposal to pre-specify and lock a two-probe region-level rule in an independent threshold-setting cohort before any validation. In GSE178610, positivity was preservation-dependent (higher in FFPE than fresh-frozen; Supplementary Data), consistent with—but not specific for—fixation- or batch-related inflation; fresh-frozen estimates were used for cross-cohort comparison. cg27577527 was positive in 8/9 tumours (mean β=0.62) in a small 450K cohort not used in discovery (GSE93589). In the 34 GSE136791 hyperplasia samples, positivity remained high (58.8–100%), indicating a neoplasia-gradient rather than carcinoma-specific profile; hyperplasia atypia is not annotated, so this is consistent with, but does not prove, detection of premalignant lesions [25]. As a post hoc, hypothesis-generating rule derived from these same data (reported for transparency, not as a performance claim), positivity of either BOLL-region probe yielded 65/69 (94.2%) in GSE136791 carcinomas and 22/23 (95.7%) in GSE155760 with 0/13 false positives; we do not report ROC/AUC, because the only cancer-free controls (n=13) come from a different study than the GSE136791 carcinomas and 13 controls are too few for a stable estimate (upper 95% bound ≈23%)."),

("To address the EPIC-platform absence of cg27577527",
 "To address the EPIC-platform absence of cg27577527, we screened all nine EPIC-manifest probes spanning the same ZSCAN12 DMR (hg38 chr6:28,399,501–28,400,362) against the decisive intended-use-proxy background (GSE223817) and the external tumour cohorts. Three probes—cg23164203, cg20275132 and cg25666433—passed the P95 β≤0.15 gate in the approximating cohort (P95 0.088–0.120; positivity ≤0.3%) with low cervical, blood and cycle-drift backgrounds while retaining high tumour positivity (TCGA 86.8–90.3%; per-cohort metrics in Supplementary Data). At the healthy-endometrium dimension (n=17), cg23164203 (P95 0.143, bootstrap 95% CI 0.123–0.144) and cg20275132 (0.149, 95% CI 0.129–0.154) passed by point estimate, whereas cg25666433 was borderline (0.151, 95% CI 0.124–0.155, crossing the gate). The ZSCAN12 region therefore remains a candidate region with both 450K- and EPIC-compatible readouts. These healthy-endometrium estimates are pipeline-dependent: under GMQN-normalised values from the same 17 samples, all three substitutes exceed the gate (P95 0.160–0.167), so substitute compliance at this dimension is unresolved and will depend on the locked validation pipeline; we do not interpret sub-0.01 point differences (e.g., 0.149 versus 0.151) as meaningful."),

("We next tested whether panel loci show",
 "We next tested whether panel loci show a quantitative methylation gradient across the neoplastic continuum. Within GSE136791 (EPIC), methylation was consistently higher in carcinoma (n=69) than in hyperplasia (n=34) for all 21 evaluable panel probes (median mean β 0.665 versus 0.601); this within-cohort contrast is the primary evidence. Extending the gradient to benign endometrium is descriptive, because the benign reference (13 endometrial controls from GSE155760) came from a different cohort; with that reference, mean β increased monotonically from benign through hyperplasia to carcinoma for all 21 probes (median 0.152, 0.601, 0.665; both BOLL probes followed the same ordering). The carcinoma>hyperplasia ordering was reproduced in GSE67116 (450K; median 0.533 versus 0.327), which contributed to discovery and is therefore not independent evidence. Hyperplasia atypia is not annotated in either cohort; the intended use is triage of premenopausal abnormal uterine bleeding (target condition: EC and atypical hyperplasia; reference standard: histopathology), in which detecting atypical hyperplasia is clinically valuable; because atypia is unannotated, hyperplasia positivity is ambiguous—premalignant detection, non-atypical false positivity and cohort or technical bias cannot be separated—so we interpret it as a neoplastic-continuum signal and avoid carcinoma-specificity claims."),

("Several limitations warrant emphasis",
 "Several limitations warrant emphasis. The healthy-donor background estimates rest on 17 samples, so P95 statistics are unstable (bootstrap 95% CI for cg07495363 spans 0.069–0.182; per-probe maximum, P90 and proportion above 0.15 in Supplementary Data—for several probes a minority of healthy donors exceed 0.15 even where the P95 passes, so the gate is a screening heuristic rather than a specificity estimate), and bootstrap intervals for extreme quantiles in small cohorts are driven by one or two extreme observations; menopause status was taken from the Xena clinical matrix and was not histologically confirmed. This is an in silico analysis in which selection and coverage evaluation partially share data, so performance estimates are upper bounds. The premenopausal subgroup comprised 28 tumours (cg24589459 positivity 89.3%, 95% CI 72.8–96.3%), external cohorts were not menopause-stratified, and any premenopausal-specific advantage remains to be demonstrated prospectively. Discovery and triage layers used different normalisation (noob versus GMQN); near-gate pass/fail status changed for 11 of 26 probes between pipelines (both lead probes robust), so thresholds are heuristic and pipeline-bound. ZSCAN12 and CELF4 illustrate platform dependence (absent from EPIC and 450K respectively); urine/ctDNA suitability was inferred from blood-cell background only. The comb-p-like merger does not model inter-probe correlation (potentially optimistic region P values), hence the bumphunter cross-check (chromosome-wise empirical P≤0.002, k=0 of B=500 permutations with the +1 correction (k+1)/(B+1)=1/501≈0.002; not a genome-wide FWER). True self-sampling performance additionally depends on tumour-DNA shedding, cellular mixing, DNA degradation and bisulfite conversion efficiency. Tissue-cohort corroboration used tumour tissue, not the intended sampling compartments; benign external controls number only 13; GSE178610 lacks non-malignant controls; and FFPE positivity is not marker performance. GSE223817 lacks per-sample annotation of menopausal status, AUB presentation and benign uterine diagnoses, so this dimension approximates, rather than strictly matches, the intended-use population. No wet-lab validation has been performed; the proposed panel is designed for a premenopausal cohort with matched benign AUB controls."),
]

doc = Document(SRC)
miss = []
done = set()
for p in doc.paragraphs:
    t = p.text.strip()
    for anchor, new in REWRITES:
        if anchor in done:
            continue
        if t.startswith(anchor.rstrip('.')) or t.startswith(anchor):
            for r in list(p.runs):
                r._element.getparent().remove(r._element)
            p.add_run(new)
            done.add(anchor)
            break

for anchor, _ in REWRITES:
    if anchor not in done:
        miss.append(anchor)
print('MISS:', miss if miss else 'none')
doc.save(SRC)

# word count
doc2 = Document(SRC)
words = sum(len(p.text.split()) for p in doc2.paragraphs if p.text.strip())
print('word count now:', words, '(was 7226, v9.10 6474)')
